name: Update Medium Posts

on:
  schedule:
    - cron: "0 */6 * * *" # update setiap 6 jam
  workflow_dispatch: # bisa manual run

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch Medium posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://medium.com/feed/@rifaldo"
